#pragma once
#ifndef MYTHRIL_AST_PARSER_DEFAULTS_H
#define MYTHRIL_AST_PARSER_DEFAULTS_H

#define ARGS_INIT_CAPACITY          4
#define PARAM_INIT_CAPACITY         4

#define ENUM_TYPES_INIT_CAPACITY    4

#define STMTS_INIT_CAPACITY         8

#endif // !MYTHRIL_AST_PARSER_DEFAULTS_H
